name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm install

      - name: Lint TypeScript
        run: npm run lint --if-present

      - name: Run tests
        run: npm test --if-present

      # ⚡ Nouveau : Validation Swagger
      - name: Validate Swagger YAML
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: swagger.yaml
